<#
Module manifest for the 'cNtfsAccessControl' DSC resource module.
Generated by Serge Nikalaichyk.
#>

@{
    ModuleVersion = '1.3.0'
    GUID = '8c4ba730-7d8e-4522-8c7e-a1b45108594c'
    Author = 'Serge Nikalaichyk'
    Copyright = '(c) 2016 Serge Nikalaichyk. All rights reserved.'
    Description = 'The cNtfsAccessControl module contains DSC resources for NTFS access control management.'
    PowerShellVersion = '4.0'
    CLRVersion = '4.0'
    FunctionsToExport = '*'
    CmdletsToExport = '*'
    VariablesToExport = '*'
    AliasesToExport = '*'
    PrivateData = @{
        PSData = @{
            Tags = @('AccessControl', 'ACL', 'DesiredStateConfiguration', 'DirectorySecurity', 'DSC', 'FileSecurity', 'FileSystem', 'FileSystemSecurity', 'NTFS', 'PSModule')
            LicenseUri = 'https://github.com/SNikalaichyk/cNtfsAccessControl/blob/master/LICENSE'
            ProjectUri = 'https://github.com/SNikalaichyk/cNtfsAccessControl'
        }
    }
}
