[ClassVersion("1.1.0.0")]
class cNtfsAccessControlInformation
{
    [Write, Description("Indicates whether to allow or deny access to the target item."), ValueMap{"Allow","Deny"}, Values{"Allow","Deny"}] String AccessControlType;
    [Write, Description("Indicates the access rights to be granted to the principal.")] String FileSystemRights[];
    [Write, Description("Indicates the inheritance type of the permission entry."), ValueMap{"None","ThisFolderOnly","ThisFolderSubfoldersAndFiles","ThisFolderAndSubfolders","ThisFolderAndFiles","SubfoldersAndFilesOnly","SubfoldersOnly","FilesOnly"}, Values{"None","ThisFolderOnly","ThisFolderSubfoldersAndFiles","ThisFolderAndSubfolders","ThisFolderAndFiles","SubfoldersAndFilesOnly","SubfoldersOnly","FilesOnly"}] String Inheritance;
    [Write, Description("Indicates whether the permission entry is not propagated to child objects.")] Boolean NoPropagateInherit;
};

[ClassVersion("1.1.0.0"), FriendlyName("cNtfsPermissionEntry")]
class cNtfsPermissionEntry : OMI_BaseResource
{
    [Write, Description("Indicates if the principal has explicitly assigned permissions on the target path."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
    [Key, Description("Indicates the path to the target item.")] String Path;
    [Write, Description("Obsolete. Indicates whether the target item is a Directory or a File."), ValueMap{"Directory","File"}, Values{"Directory","File"}] String ItemType;
    [Key, Description("Indicates the identity of the principal.")] String Principal;
    [Write, Description("Indicates the access control information in the form of an array of instances of the cNtfsAccessControlInformation CIM class."), EmbeddedInstance("cNtfsAccessControlInformation")] String AccessControlInformation[];
};
