
[ClassVersion("1.0.0"), FriendlyName("Printer")]
class VE_Printer : OMI_BaseResource
{
    [Key, Description("Specifies the name of the printer")] String Name;
    [Required, Description("Specifies the name of the printer driver for the printer")] String DriverName;
    [Required, Description("Specifies the name of the port used or created for the printer")] String PortName;
    [Write, Description("Specifies the text to add to the Comment field for the specified printer")] String Comment;
    [Write, Description("Specifies the location of the printer")] String Location;
    [Write, Description("Specifies whether or not the printer is published in the network directory service")] Boolean Published;
    [Write, Description("Specifies the share name of the printer")] String ShareName;
    [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
};
